language: go
sudo: false
#env: GIMME_OS=windows GIMME_ARCH=amd64
before_script:
 - go get -v ./...
install:
 - export GOPATH="${TRAVIS_BUILD_DIR}/go-deps/:$GOPATH"
 - export PATH="${TRAVIS_BUILD_DIR}/go-deps/bin:$PATH"
script:
 - go install -v ./...